// autogenerated file (GitSha.py), do not edit unless knowing what you're doing
#pragma once
#define GIT_SHA  "915aba1c1bae41f31473deb76068820ee45435ff"
#define GIT_SHA_SHORT  "915aba1"
#define COMMIT_DATE  "22/07/17 (19:13)"
