// autogenerated file (GitSha.py), do not edit unless knowing what you're doing
#pragma once
#define GIT_SHA  "828d2b84e5f4197bd6499767dd2ad53861735c2c"
#define GIT_SHA_SHORT  "828d2b8"
#define COMMIT_DATE  "24/07/17 (16:04)"
