// autogenerated file (GitSha.py), do not edit unless knowing what you're doing
#pragma once
#define GIT_SHA  "a512ab3b1490c8d40c45f54db3252d224dd35c2d"
#define GIT_SHA_SHORT  "a512ab3"
#define COMMIT_DATE  "28/07/17 (13:16)"
