// autogenerated file (GitSha.py), do not edit unless knowing what you're doing
#pragma once
#define GIT_SHA  "0ab6802249fdd811b8caaa4a7d9212a0ea1cd81c"
#define GIT_SHA_SHORT  "0ab6802"
#define COMMIT_DATE  "12/08/17 (15:55)"
