// autogenerated file (GitSha.py), do not edit unless knowing what you're doing
#pragma once
#define GIT_SHA  "ea8c6549cab0f3b8ea8724f34912bec53c980097"
#define GIT_SHA_SHORT  "ea8c654"
#define COMMIT_DATE  "14/09/17 (20:22)"
