// autogenerated file (GitSha.py), do not edit unless knowing what you're doing
#pragma once
#define GIT_SHA  "d0652a59f6cbab939f2b4c1bd6b6784b0c1232a6"
#define GIT_SHA_SHORT  "d0652a5"
#define COMMIT_DATE  "28/10/17 (02:07)"
