
// this file is autogenerated in deploy builds to set full build name
// BUILD_VERSION_UID is only used in auto updater
#pragma once
#define BUILD_VERSION_UID "Unknown"
#define GIT_SHA "0"
#include "Utils/VersionTriplet.h"

