
// this file is autogenerated in deploy builds to set full build name
// BUILD_VERSION_UID is only used in auto updater
#pragma once
#define BUILD_VERSION_UID "osx_x86_64"
#define GIT_SHA "1f04d7b8"
#include "Utils/VersionTriplet.h"

