// this file is autogenerated in deploy builds to set full build name
// BUILD_VERSION_UID is only used in auto updater
#define BUILD_VERSION_UID "None"


namespace ProjectInfo
{
    extern const char* const  projectName;
    extern const char* const  versionString;
    extern const int          versionNumber;
}
